# Generated by Django 4.2.4 on 2023-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_restaurant_address_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
    ]
