# Generated by Django 4.2.4 on 2023-08-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_time',
            field=models.IntegerField(),
        ),
    ]
