# Generated by Django 4.2.4 on 2023-08-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_wishlist_date_planned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='tried',
        ),
    ]
